package com.hero.wireless.web.entity.business;

import com.hero.wireless.web.entity.base.BaseEntity;

import java.util.Date;

/**
 * 合作期限台账实体类
 */
public class CooperationPeriod extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperation_period.Id
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperation_period.Enterprise_No
     */
    private String enterprise_No;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperation_period.Product_No
     */
    private String product_No;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperation_period.Sub_Code
     */
    private String sub_Code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperation_period.Start_Date
     */
    private Date start_Date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperation_period.End_Date
     */
    private Date end_Date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperation_period.Contract_Url
     */
    private String contract_Url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperation_period.Status_Code
     */
    private String status_Code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperation_period.Remark
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cooperation_period.Create_Date
     */
    private Date create_Date;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getEnterprise_No() {
        return enterprise_No;
    }

    public void setEnterprise_No(String enterprise_No) {
        this.enterprise_No = enterprise_No;
    }

    public String getProduct_No() {
        return product_No;
    }

    public void setProduct_No(String product_No) {
        this.product_No = product_No;
    }

    public String getSub_Code() {
        return sub_Code;
    }

    public void setSub_Code(String sub_Code) {
        this.sub_Code = sub_Code;
    }

    public Date getStart_Date() {
        return start_Date;
    }

    public void setStart_Date(Date start_Date) {
        this.start_Date = start_Date;
    }

    public Date getEnd_Date() {
        return end_Date;
    }

    public void setEnd_Date(Date end_Date) {
        this.end_Date = end_Date;
    }

    public String getContract_Url() {
        return contract_Url;
    }

    public void setContract_Url(String contract_Url) {
        this.contract_Url = contract_Url;
    }

    public String getStatus_Code() {
        return status_Code;
    }

    public void setStatus_Code(String status_Code) {
        this.status_Code = status_Code;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Date getCreate_Date() {
        return create_Date;
    }

    public void setCreate_Date(Date create_Date) {
        this.create_Date = create_Date;
    }
}
