package com.hero.wireless.web.entity.business;

import com.hero.wireless.web.entity.base.BaseEntity;

import java.util.Date;

public class Product extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.Id
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.Name
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.No
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.Trade_Type_Code
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String trade_Type_Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.Status_Code
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String status_Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.Intercept_Strategy_Id
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private Integer intercept_Strategy_Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.Create_Date
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private Date create_Date;

    /**
     * 号码台账扩字段(v4.3):码号使用类型
     * This field corresponds to the database column product.Code_Type
     */
    private String code_Type;

    /**
     * 号码台账扩字段(v4.3):归属合作方企业编号
     * This field corresponds to the database column product.Enterprise_No
     */
    private String enterprise_No;

    /**
     * 号码台账扩字段(v4.3):启用日期
     * This field corresponds to the database column product.Activate_Date
     */
    private Date activate_Date;

    /**
     * 号码台账扩字段(v4.3):码号资源详情
     * This field corresponds to the database column product.Number_Detail
     */
    private String number_Detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.Id
     *
     * @return the value of product.Id
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.Id
     *
     * @param id the value for product.Id
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.Name
     *
     * @return the value of product.Name
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.Name
     *
     * @param name the value for product.Name
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.No
     *
     * @return the value of product.No
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.No
     *
     * @param no the value for product.No
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setNo(String no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.Trade_Type_Code
     *
     * @return the value of product.Trade_Type_Code
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getTrade_Type_Code() {
        return trade_Type_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.Trade_Type_Code
     *
     * @param trade_Type_Code the value for product.Trade_Type_Code
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setTrade_Type_Code(String trade_Type_Code) {
        this.trade_Type_Code = trade_Type_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.Status_Code
     *
     * @return the value of product.Status_Code
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getStatus_Code() {
        return status_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.Status_Code
     *
     * @param status_Code the value for product.Status_Code
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setStatus_Code(String status_Code) {
        this.status_Code = status_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.Intercept_Strategy_Id
     *
     * @return the value of product.Intercept_Strategy_Id
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public Integer getIntercept_Strategy_Id() {
        return intercept_Strategy_Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.Intercept_Strategy_Id
     *
     * @param intercept_Strategy_Id the value for product.Intercept_Strategy_Id
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setIntercept_Strategy_Id(Integer intercept_Strategy_Id) {
        this.intercept_Strategy_Id = intercept_Strategy_Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.Create_Date
     *
     * @return the value of product.Create_Date
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public Date getCreate_Date() {
        return create_Date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.Create_Date
     *
     * @param create_Date the value for product.Create_Date
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setCreate_Date(Date create_Date) {
        this.create_Date = create_Date;
    }

    public String getCode_Type() {
        return code_Type;
    }

    public void setCode_Type(String code_Type) {
        this.code_Type = code_Type;
    }

    public String getEnterprise_No() {
        return enterprise_No;
    }

    public void setEnterprise_No(String enterprise_No) {
        this.enterprise_No = enterprise_No;
    }

    public Date getActivate_Date() {
        return activate_Date;
    }

    public void setActivate_Date(Date activate_Date) {
        this.activate_Date = activate_Date;
    }

    public String getNumber_Detail() {
        return number_Detail;
    }

    public void setNumber_Detail(String number_Detail) {
        this.number_Detail = number_Detail;
    }
}